name: spotify_search_app
description: A modern Flutter app with Spotify API integration for intelligent artist search
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  qr_flutter: ^4.1.0
  
  # State Management
  provider: ^6.0.5
  
  # HTTP & API
  http: ^1.1.0
  crypto: ^3.0.3
  
  # Authentication
  flutter_web_auth_2: ^3.0.5
  flutter_secure_storage: ^9.0.0
  
  # AI - Google Gemini
  google_generative_ai: ^0.2.2
  
  # Audio
  audioplayers: ^5.2.1
  
  # Utilities
  intl: ^0.18.1
  shimmer: ^2.0.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
